export default {
    name: "parisa aghaii",
    home: "HOME",
    about: "ABOUT",
    resume: "RESUME",
    portfolios: "PORTFOLIOS",
    contact: "CONTACT",
    hi: "Hi, I am",
    hi2: "",
    desc: " I am a frontend web developer.I can provide clean cod and pixel perfect disign.I also make make websit & more intractive with web animations.",
    aboutme: "ABOUT ME",
    services: "SERVICES",
    fullname: "Full Name",
    age: "Age",
    nationality: "Nationality",
    languages: "Languages",
    phone: "Phone",
    years: " Years",
    iranian: "Iranian",
    persian: "Persian",
    english: "English",
    downloadcv: "DOWNLOAD CV",
    webdesign: "Web Design",
    webdevelopment: "Web Development",
    mobileapp: "Mobile Application",
    servicedesc: "hello i am parisa i am a iranian girl and i love react also i can speack English",
    myskills: "MY SKILLS",
    workingSteps: [
        { id: -1, Date: "", title: "", subtitle: "", content: "" },
        { id: 0, Date: "2018-2019", title: "Frontend Web Developer ", subtitle: "Abc Univercity", content: "Hello i am parisa and i love react becuse its relly good" },
        { id: 1, Date: "2018-2019", title: "Backend Web Developer ", subtitle: "Abc Univercity", content: "Hello i am parisa and i love react becuse its relly good" },
        { id: -2, Date: "", title: "", subtitle: "", content: "" },
    ],
    educationalSteps: [
        { id: -1, Date: "", title: "", subtitle: "", content: "" },
        { id: 0, Date: "2018-2019", title: "Master of Science ", subtitle: "Abc Univercity", content: "Hello i am parisa and i love react becuse its relly good" },
        { id: 1, Date: "2018-2019", title: "Bachelor of Science", subtitle: "Abc Univercity", content: "Hello i am parisa and i love react becuse its relly good" },
        { id: 3, Date: "2018-2019", title: "High School Graduation", subtitle: "Abc Univercity", content: "Hello i am parisa and i love react becuse its relly good" },
        { id: -2, Date: "", title: "", subtitle: "", content: "" },
    ],
    workingexperience: " Working Experience",
    educationalqualification: "Educational Qualification",
    contactme: "CONTACT ME",
    getintouch:"Get In Touch",
    enteryourname:"Enter your name",
    enteryouremail:"Enter your email",
    enteryoursubject:"Enter your subject",
    enteryourmessage:"Enter your Message",
    sendmessage:"Send Message",
    icontitlephon: "Phone",
    icontitleemail: "Email",
    icontitleaddres: "Address",
    addrescontact: "IRAN-Tehran",
    portfolioList  :[
        { id: 1, title: "react developer", desc: "react js student ", image: "https://csharpcorner.azureedge.net/article/what-and-why-reactjs/Images/React%20Properties.jpg" },
        { id: 2, title: "react developer", desc: "react js student ", image: "https://itsg-global.com/wp-content/uploads/2016/09/react-js-to-use-or-not-to-use.png" },
        { id: 3, title: "react developer", desc: "react js student ", image: "https://cdn.evilmartians.com/front/posts/optimizing-react-virtual-dom-explained/cover-a1d5b40.png" },
        { id: 4, title: "react developer", desc: "react js student ", image: "https://codefriend.ir/wp-content/uploads/2020/02/one-year-of-react-native.png" },
        { id: 5, title: "react developer", desc: "react js student ", image: "https://miro.medium.com/max/3200/1*qXcjSfRj0C0ir2yMsYiRyw.jpeg" },
        { id: 6, title: "react developer", desc: "react js student ", image: "https://miro.medium.com/max/3840/1*yjH3SiDaVWtpBX0g_2q68g.png" },
    ],
}